version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-app-ci
    restart: always
    ports:
      - "3101:3000"
    env_file:
      - .env
    networks:
      - ci-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ci-network:
    driver: bridge
